### ISSUE TITLE
Avoiding HTTP Error  403

### ISSUE THREAD

**Issue by sharshit** [PrasadG193/covaccine-notifier#13]
I was getting this error after ~1 hour
Error: Failed to fetch appointment sessions: Request failed with statusCode: 403

**Comment by PrasadG193** [comment]
Reading response, looks like they have started applying stricter rate limiting
```
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
```

**Comment by shakti-garg** [comment]
@PrasadG193 This error is not due to rate limiting as their new spec is 100 API calls per 5 minutes per IP and this code is doing 5 to 7 API calls per 5 mins.

The error was due to the fact that since yesterday, API calls are expecting an User Agent Header.

**Comment by shakti-garg** [comment]
@PrasadG193 
As this issue is now resolved with new merged PR(#14) and older release is not working, we need a new release. Please call out if you need any help from me.

**Comment by fun-works** [comment]
I have taken the latest code, but I am still getting error 403

**Comment by abhiunix** [comment]
Same here!

**Comment by nirzarbhaidkar** [comment]
Booking Response Code: 400
Booking Response : {"errorCode":"APPOIN0043","error":"Minimum age criteria is 18 years and maximum age 44 for this center"}
Response: 400 : {"errorCode":"APPOIN0043","error":"Minimum age criteria is 18 years and maximum age 44 for this center"}

**Comment by PrasadG193** [comment]
We have tagged a new release, please try now. Closing the issue. Please feel free to reopen if it still exists
