### ISSUE TITLE
Add option to select free/paid vaccination center

### ISSUE THREAD

**Issue by sohm22** [PrasadG193/covaccine-notifier#20]

**Comment by shreyas-sriram** [comment]
@PrasadG193 This is similar to my previous PR, do you want me to implement this?

**Comment by PrasadG193** [comment]
@shreyas-sriram sure, please go ahead if you want to pick this up :)

**Comment by shreyas-sriram** [comment]
@sohm22 @PrasadG193 Can we close this issue?

**Comment by sohm22** [comment]
thanks @shreyas-sriram
