### ISSUE TITLE
Getting error while sending the email 

### ISSUE THREAD

**Issue by shre2398** [PrasadG193/covaccine-notifier#22]
Got following error : 
```
2021/05/10 04:51:34 Found available slots, sending email
Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials d63sm18304741pjk.10 - gsmtp
Usage:
  covaccine-notifier [FLAGS] [flags]
```

**Comment by PrasadG193** [comment]
@shre2398 do you have 2FA enabled on your gmail account?

**Comment by shreyas-sriram** [comment]
Enable 2FA and generate an **app password**. I guess that's the only way.
https://myaccount.google.com/apppasswords

**Comment by shre2398** [comment]
Yes, I enabled my acc for less secure apps. Its working now. Closing the issue.

**Comment by PrasadG193** [comment]
@shre2398 the ideal way is to generate an app passwords (token) instead of allowing less secure apps. Please check - https://support.google.com/accounts/answer/185833?p=InvalidSecondFactor&visit_id=637554658548216477-2576856839&rd=1. We have added note about this in the README
