### ISSUE TITLE
Invalid state name

### ISSUE THREAD

**Issue by arijita12** [PrasadG193/covaccine-notifier#25]
When i am providing West Bengal as the state name its giving invalid name where as in the response same name has been mentioned.

**Comment by PrasadG193** [comment]
@arijita12 could you please post how are you passing the `--state` arg?

**Comment by arijita12** [comment]
@PrasadG193  covaccine-notifier --state West Bengal --district West Bardhaman --age 70

**Comment by PrasadG193** [comment]
@arijita12 can you try adding the name is double quotes - 
`covaccine-notifier --state "West Bengal" --district "West Bardhaman" --age 70`?
