### ISSUE TITLE
False alarm for slot availability of vaccine dose 1

### ISSUE THREAD

**Issue by sohm22** [PrasadG193/covaccine-notifier#35]
below snippet from response

```
available_capacity: 1
available_capacity_dose1: 0
available_capacity_dose2: 1
```

**Comment by abhinavsinha1991** [comment]
Needs filtering for dose1 vs dose 2 to report correctly

**Comment by abhinavsinha1991** [comment]
Fixed: https://github.com/abhinavsinha1991/covaccine-notifier/commit/104ac3cecd853366c68060d4ba78e01d50e73f3f

Tested: https://github.com/abhinavsinha1991/covaccine-notifier/blob/main/screenshot1.jpeg

**Comment by PrasadG193** [comment]
@abhinavsinha1991 do you mind raising a PR since you have already fixed this?

**Comment by PrasadG193** [comment]
Fixed with - https://github.com/PrasadG193/covaccine-notifier/pull/37
